name: Actualizar JSON Naval Action

on:
  schedule:
    - cron: '0 11 * * *'  # 13:00 CEST = 11:00 UTC
  workflow_dispatch:      # Permite ejecución manual desde GitHub

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        run: python actualizar_json.py

      - name: Subir archivos JSON al servidor por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: datos_actualizados
          server-dir: /public_html/data

      - name: Subir ports.js al servidor por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: mi-mapa
          server-dir: /public_html/mi-mapa

